theme: jekyll-theme-minimal
title: "InstaPython App by Micha Birklbauer"
description: "Project Website for InstaPython App - A graphical interface for InstaPython"
logo: https://raw.githubusercontent.com/t0xic-m/t0xic-m.github.io/master/avatar.jpg
show_downloads: "true"
github:
  zip_url: https://github.com/t0xic-m/instapython-app/archive/master.zip
  tar_url: https://github.com/t0xic-m/instapython-app/archive/master.tar.gz
